language: java
jdk:
- oraclejdk8
env:
  global:
    - PRE_RELEASE_BRANCH=dev
    - RELEASE_BRANCH=master
    - secure: YSE6xMF1f9uNEaCHkyrRNx2GiwC7V5FwUNWsZPtOyz3aifvaJs31PF/7S6WTywHG0RXKk76oQ15jalUs+tlo8ssBhZBbYHOnqn5MYE8Ml/61xV++V0Nj1janH4+EA48OUaZANuCuc+dPkdQ3cAAv2S2eUnd+MLX3elCmSyZ8+8af0Vi5672FJ2GzYiXxtmo4JiwqtdkN26WKf2rMQYGzb1xdQ3KoVQ5GeMxwiaHRoobMGblwSVVZrlY5cISA0LJYLo64CpjiwC+7Log0M6E3EhqXITRux4TtsuHndV9Tbf1aMLCHvcKsSVFyZRNvyuhrRJAARk9vKPRn2de+tGv1hsFiYx2bt8V3X7z1vbiEECzGMik0G3ocCeRkHCovTt0zcCJjidvyRtEUYiuACJA/k5ZGXsRhqw5tssupB2AsSDSo48mn2xB4Ptc9R32bU0gA1T+FFQTa9cV37F+6RALHRJtcnvnevB46Ysx7ypQUqxDfAXMrXM/OsNRgh95DJ0uq5IkC1T6xZhrbwNmi2QlsLs5JYMSJnUfY1x7gLAZWax3QOCwFRaXaNKXtC+3a4vqt5BwKaHG0//5yE9IKPWBHFxjr9uMdKm337gWKyZ0e4b5uHgXeB1378vJ++0JB047zN3SSA4lua4hKOc6Cwb2XypgldqTb18G9oAgaEdh3sUg=
services: mongodb
before_deploy: source ./scripts/pre-release.sh
after_deploy: source ./scripts/push-version.sh
deploy:
  provider: releases
  skip_cleanup: true
  file: target/*.jar
  on:
    tags: false
    all_branches: true
    condition: "$TRAVIS_BRANCH = $PRE_RELEASE_BRANCH || $TRAVIS_BRANCH = $RELEASE_BRANCH"
  api_key:
    secure: YsyYOVOMCaOAXCSi0kQTEmtV8QhO1PVjmEKr4NS/AuqohcgC3wgMoSNG8bVaw4drVJCUC5V+eEWnB/jWrtaQAGp8LK1xTIhRQe/AnoQv41lnYZ9LG3yaUv+ECO0kda9H0SiwaHtavxx2S81aTm++Kr88zLKfA+rvW+6xaq4smih8kVwTpEaNmXjJeI3dA0M53Y55jdgo/SV3C1kPUVkGSBmx/mnM75G8kf0UrDJNYBIGgJYv8XUww7uWRXKjU3DdFV/bd2ELAcmxmF3lqDc9gVUpC7WN2ywGP8oB8KcUFabqTo4OXAZ3RunaJc7ZrAoE89eMnCuzdnsBWSiWRyhLupPXRjsdcB9jjUPeEdAlGjs13x9zF7S5aXAhXK1CSvtccdH5AdSn/CfebvQVKeGMGeuajIOuHjgEqWqTYq4izhSR6Nq+LDZMpz7iEqzHa6uHhifHlmray4Hu7sKdCrF2PZQBXcBbpUYDJu/I6e58C5+b+icchPxAhvE7lNeoAXtHc0eseK2TTzbb6oju0/Cf9c6RatMf3Q2lHfVeQZGE2vaZXYIy/UATSjdAfuk8Z9an8bMtjK+HKvrpI6LlKj8+a1hj1liRT/xrWfb5p+JZF+tPhjihDeHMbeu/+kquCXT2UGJ8pTVpN0nAyjNMbnmysQbk+9Y+5qrtC08jdoRp2eY=
